defaults:
    - agent: maddpg

# Experiment Settings
env: simple
discrete_action_space: true

experiment: vanilla
seed: 0
num_seed_steps: 5000

num_train_steps: 1e5
replay_buffer_capacity: ${num_train_steps}

eval_frequency: 5000
num_eval_episodes: 5

common_reward: true

ou_exploration_steps: 10000
ou_init_scale: 0.3
ou_final_scale: 0

device: cpu

# Logging Settings
log_frequency: 5000
log_save_tb: true
save_video: true


# hydra configuration
hydra:
    run:
        dir: ./experiment/${now:%Y.%m.%d}/${now:%H%M}_${env}_${agent.name}_${experiment}