defaults:
    - agent: maddpg

# Experiment Settings
env: simple

experiment: vanilla
seed: 0
num_seed_steps: 5000 # 5000

num_train_steps: 1e6
replay_buffer_capacity: ${num_train_steps}

eval_frequency: 10000
num_eval_episodes: 10

common_reward: true

device: cpu

# Logging Settings
log_frequency: 10000
log_save_tb: true
save_video: true


# hydra configuration
hydra:
    run:
        dir: ./experiment/${now:%Y.%m.%d}/${now:%H%M}_${agent.name}_${experiment}